FROM python:3.9-slim-buster

COPY ./requirements.txt /app/requirements.txt

WORKDIR /app

RUN pip3 install --upgrade pip
RUN pip3 install -r requirements.txt

RUN python3 -m pip install mypy
RUN pip3 install -U sqlalchemy-stubs
RUN pip3 install types-flask-sqlalchemy

COPY . /app

ENTRYPOINT ["mypy"]