search_songs:
  get_closest_cluster:
    features: 
      - danceability
      - energy
      - loudness
      - speechiness
      - acousticness
      - instrumentalness
      - liveness
      - valence
      - tempo
    target: clusterId