search_songs:
  get_closest_cluster:
    features: 
      - danceability
      - energy
      - loudness
      - speechiness
      - acousticness
      - instrumentalness
      - liveness
      - valence
      - tempo
preprocessing:
  clean:
    col_mapper: {'name':'title', 'duration_ms':'duration', 'uri':'track_uri'}
    features:
      - danceability
      - energy
      - key
      - loudness
      - speechiness
      - acousticness
      - instrumentalness
      - liveness
      - valence
      - tempo
      - title
      - duration
      - track_uri
  featurize:
    features:
      - danceability
      - energy
      - key
      - loudness
      - speechiness
      - acousticness
      - instrumentalness
      - liveness
      - valence
      - tempo
      - title
      - duration
      - track_uri
model:
  get_model:
    cols:
      - danceability
      - energy
      - loudness
      - speechiness
      - acousticness
      - instrumentalness
      - liveness
      - valence
      - tempo
    k: 5
    seed: 42
evaluate_model:
  assign_new_labels:
    features:
      - danceability
      - energy
      - loudness
      - speechiness
      - acousticness
      - instrumentalness
      - liveness
      - valence
      - tempo
    col_mapper: {'name':'title', 'duration_ms':'duration', 'uri':'track_uri'}
    clean_features:
      - danceability
      - energy
      - key
      - loudness
      - speechiness
      - acousticness
      - instrumentalness
      - liveness
      - valence
      - tempo
      - title
      - duration
      - track_uri