search_songs:
  get_closest_cluster:
    features: 
      - danceability
      - energy
      - loudness
      - speechiness
      - acousticness
      - instrumentalness
      - liveness
      - valence
      - tempo
    target: clusterId
preprocessing:
  clean:
    col_mapper: {'name':'title', 'duration_ms':'duration', 'uri':'track_uri'}
    features:
      - danceability
      - energy
      - key
      - loudness
      - speechiness
      - acousticness
      - instrumentalness
      - liveness
      - valence
      - tempo
      - title
      - duration
      - track_uri
  featurize:
    features:
      - danceability
      - energy
      - key
      - loudness
      - speechiness
      - acousticness
      - instrumentalness
      - liveness
      - valence
      - tempo
      - title
      - duration
      - track_uri
model:
  get_models_dict:
    cols:
      - danceability
      - energy
      - loudness
      - speechiness
      - acousticness
      - instrumentalness
      - liveness
      - valence
      - tempo
    k_range: [3,4,5,6,7,8,9,10]
    seed: 42
    return_list: True
  plot_models_performance:
    k_range: [3,4,5,6,7,8,9,10]
  save_model:
    best_num: "5"